version: '3.8'

services:
  flex-api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATA_BACKEND=mock
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/properties"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  flex-api-dev:
    build:
      context: .
      target: development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATA_BACKEND=mock
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Mount data directory for persistence
      - ./data:/app/data:ro
    command: npm run dev
    profiles:
      - dev
    restart: unless-stopped
